console.log("hello");
alert("sahil");

//window object
//window object is the global object in the browser.
//It is the topmost object in the browser and it has many properties and methods.
//Some of the properties and methods of the window object are:
//1. window.location
//2. window.history
//3. window.sessionStorage
//4. window.setTimeout()
//5. window.clearTimeout()
//6. window.setInterval()
//7. window.clearInterval()
//8. window.open()
//9. window.close()

//WHAT IS DOM (Document Object Model)?
//DOM is a programming interface for HTML and XML documents. It represents the structure of a document as
//a tree-like data structure. Each node in the tree represents an element in the document.

//DOM manipulation
//DOM manipulation is the process of changing the structure of a document by adding, removing, or modifying
//elements. This can be done using JavaScript.







